# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'aes_encryption' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for aes_encryption
  pod 'CryptoSwift'
  
  #target 'aes_encryptionTests' do
   # inherit! :search_paths
    # Pods for testing
  #end

  #target 'aes_encryptionUITests' do
    # Pods for testing
  #end

end
